- name: "Set user password via prompt, if user {{ user_name }} does not exist"
  include_tasks: user_password.yml
  when: set_initial_user_password

- name: "Add {{ user_name }} to specified groups"
  include_tasks: user_groups.yml
  when: user_groups is defined

