- name: "Check if user '{{ user_name }}' does not exist on the system"
  command: getent passwd {{ user_name|quote }}
  # NOTE: getent returns 0 when key bound, and 2 when key not found in database
  register: user_not_exist
  changed_when: user_not_exist.rc == 2
  failed_when: user_not_exist.rc != 0 and user_not_exist.rc != 2

- name: "Prompt and set user '{{ user_name }}' password"
  block:
    - name: "Get user '{{ user_name }}' password, via shell prompt"
      pause:
        prompt: "Enter the new password for user '{{ user_name }}'"
        echo: yes
      register: new_password
    - name: "Set user '{{ user_name }}' password, using user-input + random-salt"
      user:
        name: "{{ user_name }}"
        group: "{{ user_name }}"
        password: "{{ new_password.user_input | password_hash(password_hash_algorithm) }}"
      become: true
      become_user: root
  when: user_not_exist is changed

