- name: "Add new user '{{ user_name }}' to system"
  ansible.builtin.user:
    name: "{{ user_name }}"
    system: "{{ is_system_user }}"
    create_home: "{{ create_home_dir }}"
    state: present
  become: true
  become_user: root

